### ISSUE TITLE
Upgrade EGCG-Core

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#104]
Reporting app uses an old version of EGCG-Core which still serialise the url manually.
The new versions have few incompatible changes that needs to be update in Reporting App
 - Configuration objects has `env_var` parameter
 - api_url take only one endpoint parameter. Serialisation of parameter will be done by the ajax call directly

**Comment by mwhamgenomics** [comment]
Fixed in #114
