### ISSUE TITLE
New page showing multiple projects 

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#146]
This new page will have the same tables as the project page but the content of the table will have multiple projects.

This will probably involve changing the lims endpoints to support multiple projects in one query.

**Comment by mwhamgenomics** [comment]
Most of this is done apart from the user interface. Could have a scroll-down menu with selectable projects, but would be a bit of work. Might be easier to have a keyword where, e.g, `projects/SGP` becomes a dynamic server-side query for all SGP projects
