### ISSUE TITLE
Remove samples from Invoicing column when they are in removed status

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#160]
In the project status page we would like the samples that have been removed from workflow to not show up in the invoicing column.
This sounds simple in theory but might need a bit of work on how the `project_status_definitions.yaml` file or is organised.
We probably will need to separate the GENOTYPING status from the INVOICED so they can have slightly different behaviour.

**Comment by lukbut** [comment]
@tcezard Why would a sample be removed from workflow? Would it be in cases of failure?

**Comment by lukbut** [comment]
@tcezard I am unable to find samples which exhibit this behaviour - @mwhamgenomics also looked into it and was not sure about it. Could it have been fixed already?
