### ISSUE TITLE
Add new column with genome version used in Sample view

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#185]
genome version used should be stored in Analysis_driver process alongside the rest of the pipeline information.

**Comment by mwhamgenomics** [comment]
We're also changing some of the column defaults:

- /runs/recent
    - hide instrument ID
- /projects/<project_id>
    - first table
        - show expected yield
        - show expected coverage
    - second table
        - show expected yield
        - show expected coverage
    - third table
        - hide run ids
        - hide initial reads in bam
        - show expected yield
        - show species
        - hide median coverage
        - hide % covered 15X
- /project_status
    - show expected yield
    - show species
- /sample/<sample>, /run/<run_id>
    - second table
        - hide passing filter reads
        - hide estimated dupl rate
- /run/<run_id>
    - top table
        - hide passing-filter reads
        - hide estimated dupl rate
        - show CV
