### ISSUE TITLE
Rename 'gender validation' to 'sex validation'

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Reporting-App#205]
Because gender != sex. See also:

- EdinburghGenomics/EGCG-Core#104
- EdinburghGenomics/Analysis-Driver#398
- EdinburghGenomics/clarity_scripts#96

**Comment by lukbut** [comment]
@mwhamgenomics Can you please update the issue status as appropriate?

**Comment by mwhamgenomics** [comment]
See #223.

**Comment by tcezard** [comment]
closed in #237
