### ISSUE TITLE
Library prep table and graph

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#222]
We'd like to be able to display the library preparation performed in the lab and get some meaningful information about them.
The would be:
 - list the library preparation with some metadata associated (date, type, nb of sample, projects)
 - have a page per library prep with list of sample and their position
 - plate view (heatmap) of the library prep with possibility of displaying specific QC metric such as adapter rate, duplicate rate, insert size, etc

couple of points:
 - Define a library prep between its start point (Create CFP Batch) to finish (Eval qPCR Quant)
 - multiple instances of start or finish step for the same plate name should be reduced to single instance
 - association between library and QC is done via sample name (no explicit support for library repeat)
 - possible to segregate sequencing QC data associated with multiple library per date (assumes that only the newest library has been sequenced)

**Comment by mwhamgenomics** [comment]
Some notes below.

The requirements are:
- a page similar to /runs/recent, except each line is a library prep
  - potentially some date filtering
- a plot of QC data per sample for one library prep
  - this can be a side-panel or a separate page

- identify a library prep as an instance of running `Eval qPCR Quant`
  - samples can go through library prep multiple times, so should be able to roll up duplicate runs
- query the Process table and filter by step name
  - QC will be attached to the processing artifacts
- we may need to merge this with QC data from NoSQL

**Comment by tcezard** [comment]
closed in #231
