### ISSUE TITLE
Project status last updated

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#225]
Add in the project/plate status a `last_update_date` field which will be the most recent change to the sample with this status.
In the project status web page background colour the cells where the `last_update_date` field is more than 1, 2  and 4 weeks.
this will not apply to the finished and removed status.

**Comment by lukbut** [comment]
Today, @tcezard suggested introducing additional keys in the existing API endpoint to make the code which deliver this functionality cleaner.
