### ISSUE TITLE
Pull and cache information from the LIMS directly

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#29]
Grabbing information from the LIMS directly would be a great advantage as it would allow us to query it quickly from the REST API.
To be fast the info will have to be cached in the database with an option to refresh the information.

Example info would be:
- the user sample id
- the species
- the Yield for quoted coverage

**Comment by mwhamgenomics** [comment]
Suggested implementation:

We add a field to the schema called `lims_cache_id`. The Rest API has an entry in the `samples` endpoint:
```python
{
    'sample_id': 'a_sample_id',
    'median_coverage': 30.2,
   'lims_cache_id': 'a_sample_id'
}
```

NoSQL database has a `lims_cache` endpoint, periodically updated with data pulled from the LIMS:
```python
{
    'sample_id': 'a_sample_id',
    'species': 'Human'
}
```

When querying `samples`, we use `embedded` (in pure Eve) or `lookup` (in aggregation) to pull in information from the `lims_cache` endpoint.

**Comment by tcezard** [comment]
With the new Lims end point we do not need to cache information from the LIMS anymore.
