### ISSUE TITLE
TypeError from charts.js on Safari

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Reporting-App#59]
When navigating to the Charts page on Safari, the following Javascript error occurs:
`TypeError: undefined is not a function (evaluating 'Array.from(new Set(runs))')`

There is also no tab title or version number on the charts page - this would be fixed by going through the template rendering function defined in `reporting_app.__init__`, rather than `fl.render_template`.

**Comment by mwhamgenomics** [comment]
Update: The problem is `Array.from`, which is supported on Safari 9, but not on Opera or Internet Explorer. Should just be able to fix the tab title/version number, and then this can be closed.

**Comment by tcezard** [comment]
This has been fixed
