### ISSUE TITLE
New page showing the Runs in the sequencers

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#69]
We will add a new page showing the runs that are currently going in the sequencers.
The first pass solution will be to create a page  that queries the LIMS for all non completed AUTOMATED-Sequence and show the samples that are running in each ones
To complement this we can also parse/display some information from the interop.
This could be done by parsing the interop in python using [illuminate](https://pypi.python.org/pypi/illuminate/), wrapping around the [c++ library from illumina](https://github.com/Illumina/interop) or a [java framework](https://github.com/NKI-GCF/Metrix)

**Comment by mwhamgenomics** [comment]
We should have two tables:
- runs currently on the sequencers
- runs recently completed/failed

This means we'll need a current/recent argument in the `lims` endpoint.
