### ISSUE TITLE
Stages endpoint

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Reporting-App#72]
At the moment, stages are a nested array in `analysis_driver_procs`. As we are intending to segment the pipeline, we will be making much more use of stages in the future. It would make more sense to have stages in their own endpoint so we can select and update them independently (this might also fix #21).

**Comment by mwhamgenomics** [comment]
This will also require a database migration from:
```python
{
    'proc_id': 'sample_A_01_01_2017_12:00:00',
    'dataset_type': 'sample',
    'dataset_name': 'sample_A',
    'start_date': '01_01_2017_12:00:00',
    'end_date': '01_01_2017_12:30:00',
    'pid': 1337,
    'status': 'finished'
    'stages': [
        {
            'stage_name': 'stage_1',
            'date_started': '01_01_2017_12:00:00',
            'date_finished': '01_01_2017_12:10:00'
            'exit_status: 0
        }
    ]
}
```
to:
```python
 {
    'proc_id': 'sample_A_01_01_2017_12:00:00',
    'dataset_type': 'sample',
    'dataset_name': 'sample_A',
    'start_date': '01_01_2017_12:00:00',
    'end_date': '01_01_2017_12:30:00',
    'pid': 1337,
    'status': 'finished'
    'stages': [1234567]
}

{
    # '_id': 1234567,
    'analysis_driver_proc': 'sample_A_01_01_2017_12:00:00',
    'stage_name': 'stage_1',
    'date_started': '01_01_2017_12:00:00',
    'date_finished': '01_01_2017_12:10:00'
    'exit_status: 0
}
```

**Comment by mwhamgenomics** [comment]
At the moment, the default `_id` is the primary key, but creating a new stage is a multi-step process. It is necessary to:
- create/push the stage to generate the _id
- retrieve it with `where={"analysis_driver_proc":"foo","stage_name":"bar"}` and select the _id
- add the _id to the proc's list of stages

**Comment by mwhamgenomics** [comment]
At the moment when MostRecentProc creates a new stage, it pushes a new `stage` entity, does a get_document in `self._stage_id' to get the `_id`, and adds it to the list of stages in `self.entity`.

The get_document in `self._stage_id` filters on `analysis_driver_proc` and `stage_name`, assuming the combination of these two will be unique. This means at the moment we can't have two stages in a pipeline with the same name. Might we want this?

**Comment by tcezard** [comment]
I think it will be ok to have a unique ```stage_name``` per ```analysis_driver_proc```. 
But if you require it to be unique maybe you should enforce it to be by adding it as a stage_id.
This way you will have a deterministic way to retrieve a stage in one step (as long as you know the name).
