### ISSUE TITLE
Runs from LIMS not showing in page because Process's UDF are not set

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#83]
The page should show the run Processes but the database query is not returning anything because the Process do not have their UDF set in the ProcessUdfView.
I do not know if we can do much about this but am recording it here anyway.

**Comment by mwhamgenomics** [comment]
In Clarity 4.2, the UDF views are deprecated. Should we try to query the underlying UDF tables directly?
