### ISSUE TITLE
Aggregation optimisation

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/Reporting-App#95]
Some of the aggregation endpoints are very slow, possibly due to any of:
- lookups across different endpoints
- not applying filters early enough
- performing many calculations for all fields present, regardless of whether they're used

This could be addressed by having a larger number of more specialised aggregation pipelines with simpler parameters, like the Lims endpoints. This way, we can perform only the calculations we need at the time.

**Comment by tcezard** [comment]
This should be addressed by #115 so closing
